# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'django_migrations',
            },
        ),
        migrations.CreateModel(
            name='PostTb01',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('post_id', models.TextField()),
                ('site_link', models.TextField(blank=True, null=True)),
                ('heading', models.TextField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('full_story', models.TextField(blank=True, null=True)),
                ('site', models.TextField(blank=True, null=True)),
                ('post_date', models.DateTimeField(blank=True, null=True)),
                ('img_src', models.TextField(blank=True, null=True)),
                ('post_link', models.TextField(blank=True, null=True)),
                ('scrap_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'post_tb_01',
            },
        ),
    ]
